---
Standards:
  -
    Title: Ada Project Practices
    Description: Virtual Environments and Projects, How to Submit
    UID: 3fc7752e2637f641643b9be4b1e005cc
    SuccessCriteria:
      - success criteria
    ContentFiles:
      -
        Type: Lesson
        UID: UZp4J5
        Path: /ada-project-practices/virtual-environments-and-projects.md
      -
        Type: Lesson
        UID: a2bcf77b287de2764675801ed5667e3b
        Path: /ada-project-practices/how-to-submit.md
  -
    Title: Viewing Party
    Description: "Unit 1 Project: Programming Fundamentals"
    UID: 687ba6c9a090110d939df3281701e530
    SuccessCriteria:
      - success criteria
    ContentFiles:
      -
        Type: Lesson
        UID: e43d905381b974a17896b57e9012c9e6
        Path: /viewing-party/intro.md
      -
        Type: Lesson
        UID: 79b4aad1f3dbbcd07eb6010a6feb8c9e
        Path: /viewing-party/submit.md
  -
    Title: Swap Meet
    Description: "Unit 1 Project: OOP"
    UID: 16de2f5e87b819e86222da4634fc6308
    SuccessCriteria:
      - success criteria
    ContentFiles:
      -
        Type: Lesson
        UID: 4ee74067a533f2df08781158cc7116b7
        Path: /swap-meet/intro.md
      -
        Type: Checkpoint
        UID: 094ab5b9366d7d1a7b26f82950f43efe
        Path: /swap-meet/submit.md
  -
    Title: Pyblobs
    Description: "Unit 1 Activity: Pyblobs"
    UID: 798f5c36-d49a-4c1c-b893-8ec1f893d44d
    SuccessCriteria:
      - success criteria
    ContentFiles:
      -
        Type: Lesson
        UID: 9a1acec7-fee1-40b2-8db9-bf1baad6b0e7
        Path: /pyblobs/pyblob-tutorial.md
      -
        Type: Lesson
        UID: 83455d48-a8b2-45e1-805f-78215ce59572
        Path: /pyblobs/activity-livecode.md
      -
        Type: Lesson
        UID: c7e070df-4327-445f-89d4-ee81605c3523
        Path: /pyblobs/activity-group-project.md
      -
        Type: Instructor
        UID: 12250d28-fc77-46ce-bf61-f5fca4751f2b
        Path: /pyblobs/roundtable.instructor.md
  -
    Title: Task List API
    Description: "Unit 2 Project: Flask"
    UID: 4MZBWO
    SuccessCriteria:
      - success criteria
    ContentFiles:
      -
        Type: Lesson
        UID: 6JDb8z
        Path: /task-list-api/intro.md
      -
        Type: Instructor
        UID: N279mX
        Path: /task-list-api/midpoint.instructor.md
      -
        Type: Lesson
        UID: NhClYt
        Path: /task-list-api/midpoint.md
      -
        Type: Checkpoint
        UID: 5vl91F
        Path: /task-list-api/submit.md
  -
    Title: Personal Portfolio Site
    Description: "Unit 3 Project: Static Site Development"
    UID: rmX3Ue
    SuccessCriteria:
      - success criteria
    ContentFiles:
      -
        Type: Lesson
        UID: FmKOc0
        Path: /personal-portfolio-site/intro.md
      -
        Type: Checkpoint
        UID: 1B0tKx
        Path: /personal-portfolio-site/submit.md
  -
    Title: Weather Report
    Description: "Unit 3 Project: Event Handling"
    UID: 8ff38305
    SuccessCriteria:
      - success criteria
    ContentFiles:
      -
        Type: Instructor
        UID: 6fc86e09
        Path: /weather-report/weather-report.instructor.md
      -
        Type: Lesson
        UID: 2eff792f
        Path: /weather-report/intro.md
      -
        Type: Checkpoint
        UID: 82e27d6e
        Path: /weather-report/submit.md
