---
Standards:
  -
    Title: Ada Project Practices
    Description: How to Submit
    UID: 3fc7752e2637f641643b9be4b1e005cc
    SuccessCriteria:
      - success criteria
    ContentFiles:
      -
        Type: Lesson
        UID: a2bcf77b287de2764675801ed5667e3b
        Path: /ada-project-practices/how-to-submit.md
  -
    Title: Viewing Party
    Description: "Unit 1 Project: Programming Fundamentals"
    UID: 687ba6c9a090110d939df3281701e530
    SuccessCriteria:
      - success criteria
    ContentFiles:
      -
        Type: Lesson
        UID: e43d905381b974a17896b57e9012c9e6
        Path: /viewing-party/intro.md
      -
        Type: Lesson
        UID: 79b4aad1f3dbbcd07eb6010a6feb8c9e
        Path: /viewing-party/submit.md
  -
    Title: AdaGrams
    Description: "Unit 1 Project: Programming Fundamentals, Pair Programming"
    UID: d82288a7-65ae-4059-a7e4-0c6abd263d0f
    SuccessCriteria:
      - success criteria
    ContentFiles:
      -
        Type: Lesson
        UID: d8f37606-19dd-4c23-b677-ab9e1a9013a2
        Path: /adagrams/intro.md
      -
        Type: Checkpoint
        UID: c1522732-a4da-43a5-b1dd-c4de8a2cc9c6
        Path: /adagrams/submit.md
  -
    Title: Swap Meet
    Description: "Unit 1 Project: OOP"
    UID: 16de2f5e87b819e86222da4634fc6308
    SuccessCriteria:
      - success criteria
    ContentFiles:
      -
        Type: Lesson
        UID: 4ee74067a533f2df08781158cc7116b7
        Path: /swap-meet/intro.md
      -
        Type: Checkpoint
        UID: 094ab5b9366d7d1a7b26f82950f43efe
        Path: /swap-meet/submit.md
  -
    Title: Pyblobs
    Description: "Unit 1 Activity: Pyblobs"
    UID: 798f5c36-d49a-4c1c-b893-8ec1f893d44d
    SuccessCriteria:
      - success criteria
    ContentFiles:
      -
        Type: Lesson
        UID: 9a1acec7-fee1-40b2-8db9-bf1baad6b0e7
        Path: /pyblobs/pyblob-tutorial.md
      -
        Type: Lesson
        UID: 83455d48-a8b2-45e1-805f-78215ce59572
        Path: /pyblobs/activity-livecode.md
      -
        Type: Lesson
        UID: c7e070df-4327-445f-89d4-ee81605c3523
        Path: /pyblobs/activity-group-project.md
      -
        Type: Instructor
        UID: 12250d28-fc77-46ce-bf61-f5fca4751f2b
        Path: /pyblobs/roundtable.instructor.md
  -
    Title: Solar System API
    Description: "Unit 2 Project: Flask, Pair Programming"
    UID: f881aa8a-2f20-4523-8c23-fb1cab6c91fb
    SuccessCriteria:
      - success criteria
    ContentFiles:
      -
          Type: Lesson
          UID: 57c735ca-c2d5-48c8-bbea-a08a2dae1345
          Path: /solar-system-api/intro.md
      -
          Type: Lesson
          UID: 3e20e0ad-a38a-4b8e-915e-8659f6f7ea24
          Path: /solar-system-api/submit-part-1.md
      -
          Type: Checkpoint
          UID: b53c0c7c-23ea-4572-a8f6-a146b7cc38d8
          Path: /solar-system-api/submit-part-2.md
  -
    Title: Task List API
    Description: "Unit 2 Project: Flask"
    UID: 4MZBWO
    SuccessCriteria:
      - success criteria
    ContentFiles:
      -
        Type: Lesson
        UID: 6JDb8z
        Path: /task-list-api/intro.md
      -
        Type: Instructor
        UID: N279mX
        Path: /task-list-api/midpoint.instructor.md
      -
        Type: Lesson
        UID: NhClYt
        Path: /task-list-api/midpoint.md
      -
        Type: Checkpoint
        UID: 5vl91F
        Path: /task-list-api/submit.md
  -
    Title: Retro Video Store 
    Description: "Unit 2 Project: Flask 2"
    UID: 43b3c7df-1b5e-40de-ade9-8f39a3536a85
    SuccessCriteria:
      - success criteria
    ContentFiles:
      -
        Type: Lesson
        UID: 94b6c609-65c4-45fa-9448-c8ab913dc1e8
        Path: /retro-video-store/intro.md
      -
        Type: Checkpoint
        UID: 7436976b-b177-4195-9502-e5a099fdefc5
        Path: /retro-video-store/submit.md
  -
    Title: Personal Portfolio Site
    Description: "Unit 3 Project: Static Site Development"
    UID: rmX3Ue
    SuccessCriteria:
      - success criteria
    ContentFiles:
      -
        Type: Lesson
        UID: FmKOc0
        Path: /personal-portfolio-site/intro.md
      -
        Type: Checkpoint
        UID: 1B0tKx
        Path: /personal-portfolio-site/submit.md
  -
    Title: Weather Report
    Description: "Unit 3 Project: Event Handling"
    UID: 8ff38305
    SuccessCriteria:
      - success criteria
    ContentFiles:
      -
        Type: Instructor
        UID: 6fc86e09
        Path: /weather-report/weather-report.instructor.md
      -
        Type: Lesson
        UID: 2eff792f
        Path: /weather-report/intro.md
      -
        Type: Checkpoint
        UID: 82e27d6e
        Path: /weather-report/submit.md
  -
    Title: React Tic-Tac-Toe
    Description: "Unit 3 Project: Event Handling in React"
    UID: d384fc84
    SuccessCriteria:
      - success criteria
    ContentFiles:
      -
        Type: Instructor
        UID: fbe844af
        Path: /react-tic-tac-toe/react-tic-tac-toe.instructor.md
      -
        Type: Lesson
        UID: 127cd416
        Path: /react-tic-tac-toe/intro.md
      -
        Type: Checkpoint
        UID: e8526c70
        Path: /react-tic-tac-toe/submit.md
  -
    Title: Full-Stack Inspiration Board
    Description: "Unit 3 Project: Connecting Front-end and Back-end Layers"
    UID: d5299051
    SuccessCriteria:
      - success criteria
    ContentFiles:
      -
        Type: Instructor
        UID: c36cc560
        Path: /full-stack-inspiration-board/full-stack-inspiration-board.instructor.md
      -
        Type: Lesson
        UID: 0425bf8b
        Path: /full-stack-inspiration-board/intro.md
      -
        Type: Checkpoint
        UID: edd56b1f
        Path: /full-stack-inspiration-board/submit.md
